name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run LemLib/pros-build
        id: build-template
        uses: LemLib/pros-build@v2.0.2
        with:
          copy_readme_and_license_to_include: true
          lib_folder_name: units

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-template.outputs.name }}
          path: ${{ github.workspace }}/template/*